# Generated by Django 4.1.4 on 2022-12-27 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='default_product.jpg', upload_to='')),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('memory', models.CharField(blank=True, max_length=16, null=True)),
                ('ram', models.CharField(blank=True, max_length=16, null=True)),
                ('camera1', models.CharField(blank=True, max_length=16, null=True)),
                ('camera2', models.CharField(blank=True, max_length=16, null=True)),
                ('battery', models.CharField(blank=True, max_length=16, null=True)),
                ('fingerprint', models.CharField(blank=True, choices=[('S', 'Back'), ('M', 'Front'), ('L', 'Side'), ('N', 'Null')], max_length=1, null=True)),
                ('face_unlock', models.BooleanField(blank=True, null=True)),
                ('processor', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.CharField(blank=True, max_length=32, null=True)),
                ('size', models.CharField(blank=True, max_length=16, null=True)),
                ('weight', models.CharField(blank=True, max_length=16, null=True)),
                ('sim', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1, null=True)),
                ('colors', models.CharField(blank=True, max_length=16, null=True)),
                ('electr', models.CharField(blank=True, max_length=16, null=True)),
                ('volume', models.CharField(blank=True, max_length=16, null=True)),
                ('max_weight', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('display', models.BooleanField(blank=True, null=True)),
                ('wifi', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
