# Generated by Django 4.1.4 on 2022-12-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
