# Generated by Django 4.1.4 on 2022-12-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='text',
        ),
    ]
